### ISSUE TITLE
shouldn't the readme.md point to the latest python3-requests i.e. v2.22.0 instead of 0.74

### ISSUE THREAD

**Issue by shirishag75** [Cheaterman/poster#1]
Hi there, 

shouldn't you link point to requests [v2.22.0](https://requests.readthedocs.io/en/master/) ?

**Comment by Cheaterman** [comment]
Agreed, in fact, I'll point to "master" just like you do. Not that it's very relevant, but hey, every little thing counts! Thanks :-)

**Comment by Cheaterman** [comment]
63770c891371546b23ee84a39f1d43642f9c2665 closes this :-)
